apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-app
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: application
        image: image
        ports:
        - containerPort: 5000