apiVersion: v1
kind: Service
metadata:
  name: challenge-svc
  labels:
    app: flask
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
    name: flask
  selector:
    app: flask
  type: ClusterIP