apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: main-

resources:
- ../../base

commonLabels:
  environment: main

transformers:
- monitoring-labels.yaml

images:
- name: image
  newName: ghcr.io/zjheyvc/devops-challenge
  newTag: 53b543e